swagger: '2.0'
info:
  title: Mock Convention 2020 Word Cloud Generator
  description: A REST api to retrieve stats from a database of words
  version: v1
basePath: /v1
consumes:
  - application/json
produces:
  - application/json
paths:
  /stats:
    get:
      description: ''
      parameters:
        - name: stat
          in: query
          description: 'Stat to be returned'
          required: true
          type: string
          default: most_used_word
          enum: [most_used_word, word_frequency]
      responses:
        '200':
          description: 'successfully returned requested stats'
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: "*"
          schema:
            $ref: '#/definitions/WordRetrieve'
        '404':
          $ref: '#/responses/NotFound'
  /articles:
    get:
      description: ''
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
          default: 0
        - name: page_size
          in: query
          description: Size of the page
          required: false
          type: integer
          default: 10
        - name: search
          in: query
          description: 'Search string'
          required: false
          type: string
      responses:
        '200':
          description: 'successfully returned articles'
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: "*"
          schema:
            $ref: '#/definitions/ArticleRetrieve'
        '404':
          $ref: '#/responses/NotFound'
responses:
  NotFound:
    description: The specified resource was not found
    schema:
      $ref: '#/definitions/Error'
definitions:
  Error:
    type: object
    properties:
      message:
        type: string
    required:
      - message
  WordRetrieve:
    required:
      - word
    type: object
    properties:
      id:
        title: Id
        type: string
      word:
        title: Word
        type: string
      date_published:
        title: DatePublished
        type: string
        format: date-time
        readOnly: true
      date_recorded:
        title: DateRecorded
        type: string
        format: date-time
        readOnly: true
  ArticleRetrieve:
    required:
      - description
      - url
    type: object
    properties:
      id:
        title: Id
        type: string
      description:
        title: Description
        type: string
      url:
        title: url
        type: string
      date_published:
        title: DatePublished
        type: string
        format: date-time
        readOnly: true
      date_recorded:
        title: DateRecorded
        type: string
        format: date-time
        readOnly: true